### PR TITLE
Merge feature/tests

### PR DESCRIPTION
**Pull request by sebGilR**
For this project, the following was accomplished:
- The game was modularized and only functions needed across files were kept public.
- Functions that are public were unit tested where applicable.

### CODE REVIEW

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED

Hi @sebGilR @dannisonarias  good job working on this guys :+1:  the good portion of the app logic have been tested already, but we can test more :slightly_smiling_face:  the goal of testing is to test all the publicly interfaced logic,

The game.js file contains a  bunch of methods that can and should be tested, you can check players and even check winners, please look into this.

Also while testing you want to provide positive and negative test cases, for example.
if `x should be a boy ` you want to also test that `x is not a boy` this takes care of edge cases and it is a pretty standard  test pattern

Please make changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

**Comment by sebGilR** [comment]
The tests suggested were added for the game module, totaling 16 tests covering most edge cases.

**Review by maelfosso — COMMENTED** [review]
# Changes required :red_circle:

Hello 

Thank you for applying the suggested changes. 
Now, Only want thing: **There is no test for the `win` function**
In fact, in all the functions using the `win` function, you defined its status but nowhere you test it. Why?
You know, it's one of the main function of the project and its corresponding test must be written.

Kindly do it and submit a new code review request.

Thanks 

Mael FOSSO

**Comment by sebGilR** [comment]
Thank you for pointing that out. Tests have been added for the WIN method.

**Review by shloch — APPROVED** [review]
## Hello @sebGilR 

Screen Shot 2020-06-20 at 11 35 29 PM

### Good to go .....

**Pull request merged**
